'use strict';

import {Router} from 'express';
import * as controller from './flow.controller';
import * as auth from '../../auth/auth.service';

var router = new Router();

router.get('/mail-merge', auth.isAuthenticated(), controller.listMailMerge);
router.post('/mail-merge', auth.isAuthenticated(), controller.createMailMerge);
router.get('/mail-merge/:code/history', auth.isAuthenticated(), controller.getMailMergeHistoryFromCode);
router.get('/mail-merge/:template/config', auth.isAuthenticated(), controller.getMailMergeConfig);
router.get('/mail-merge/:template/form', auth.isAuthenticated(), controller.getMailMergeForm);
router.get('/mail-merge/:template/email', auth.isAuthenticated(), controller.getMailMergeEmail);
router.get('/mail-merge/:template/document', auth.isAuthenticated(), controller.getMailMergeDocument);

router.get('/', auth.isAuthenticated(), controller.index); // NOT USED (auto generated by the angular-fullstack)
router.get('/:id', auth.isAuthenticated(), controller.show); // NOT USED (auto generated by the angular-fullstack)
router.post('/', auth.isAuthenticated(), controller.create); // NOT USED (auto generated by the angular-fullstack)
router.put('/:id', auth.isAuthenticated(), controller.update); // NOT USED (auto generated by the angular-fullstack)
router.delete('/:id', auth.isAuthenticated(), controller.destroy); // NOT USED (auto generated by the angular-fullstack)

module.exports = router;
